destination: ./_site
port: 4000
pygments: true
markdown: maruku
exclude: ["Gemfile", "Gemfile.lock", ".rvmrc", "vendor"]
permalink: date
maruku:
  use_tex: false
  use_divs: false
  png_dir: images/latex
  png_url: /images/latex
sass:
  syntax: scss
